version: '3'

services:
  backend:
    image: composetest:latest
    networks:
      - app-network
    expose:
      - "80"  # Ensure that the backend service is exposing port 80

  proxy:
    image: nginx:latest
    ports:
      - "80:80"  # Map port 80 of the container to port 80 of the host
    volumes:
      - ./nginx-golang:/proxy/nginx.conf
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:

